server:
  port: 8080
  #servlet:
  #  context-path: /api
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:30m} # User is going to navegate in the page during 30min.

# Data base Connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: ${POSTGRES_VICENTE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-circular-references: true

##### Spring Security and token JWT
security:
  jwt:
    expiracao: 300 # 30 minutos
    chave-assinatura: 764811743f33067f36d72dd04ce22a27
  url:
    account:
      reset: http://localhost:8080/api/users/reset-password?token=
      confirmation:
        send: http://localhost:8080/api/users/verify-email?token=
